extension WeatherConditionExtension on String {
  String toShortWeatherCondition() {
    return switch (this) {
      'Clear' => 'Clear',
      'Sunny' => 'Sunny',
      'Partly cloudy' => 'Partly cloudy',
      'Partly Cloudy ' => 'Partly cloudy',
      'Partly Cloudy' => 'Partly cloudy',
      'Cloudy' => 'Cloudy',
      'Overcast' => 'Overcast',
      'Overcast ' => 'Overcast',
      'Mist' => 'Mist',
      'Patchy rain possible' => 'Light rain',
      'Patchy rain nearby' => 'Light rain',
      'Patchy snow possible' => 'Light snow',
      'Patchy sleet possible' => 'Light sleet',
      'Patchy freezing drizzle possible' => 'Freezing drizzle',
      'Thundery outbreaks possible' => 'Thunderstorm',
      'Blowing snow' => 'Blowing snow',
      'Blizzard' => 'Blizzard',
      'Fog' => 'Fog',
      'Freezing fog' => 'Freezing fog',
      'Patchy light drizzle' => 'Light drizzle',
      'Light drizzle' => 'Light drizzle',
      'Freezing drizzle' => 'Freezing drizzle',
      'Heavy freezing drizzle' => 'Heavy drizzle',
      'Patchy light rain' => 'Light rain',
      'Light rain' => 'Light rain',
      'Moderate rain at times' => 'Moderate rain',
      'Moderate rain' => 'Moderate rain',
      'Heavy rain at times' => 'Heavy rain',
      'Heavy rain' => 'Heavy rain',
      'Light freezing rain' => 'Freezing rain',
      'Moderate or heavy freezing rain' => 'Freezing rain',
      'Light sleet' => 'Light sleet',
      'Moderate or heavy sleet' => 'Heavy sleet',
      'Patchy light snow' => 'Light snow',
      'Light snow' => 'Light snow',
      'Patchy moderate snow' => 'Moderate snow',
      'Moderate snow' => 'Moderate snow',
      'Patchy heavy snow' => 'Heavy snow',
      'Heavy snow' => 'Heavy snow',
      'Ice pellets' => 'Ice pellets',
      'Light rain shower' => 'Light rain',
      'Moderate or heavy rain shower' => 'Heavy rain',
      'Torrential rain shower' => 'Heavy rain',
      'Light sleet showers' => 'Light sleet',
      'Moderate or heavy sleet showers' => 'Heavy sleet',
      'Light snow showers' => 'Light snow',
      'Moderate or heavy snow showers' => 'Heavy snow',
      'Light showers of ice pellets' => 'Light ice pellets',
      'Moderate or heavy showers of ice pellets' => 'Heavy ice pellets',
      'Patchy light rain with thunder' => 'Rain with thunder',
      'Moderate or heavy rain with thunder' => 'Rain with thunder',
      'Patchy light snow with thunder' => 'Snow with thunder',
      'Moderate or heavy snow with thunder' => 'Snow with thunder',
      'Thundery outbreaks in nearby' => 'Thunderstorm',
      _ => this,
    };
  }
}
